name: pgAdmin4
version: 4.0.0
slug: pgadmin4
description: A PostgreSQL Management and Query tool
url: https://github.com/Expaso/hassos-addon-pgadmin4
codenotary: hans@expaso.nl
arch:
- aarch64
- amd64
- i386
- armv7
ingress: true
panel_icon: mdi:database
panel_title: pgAdmin 4
hassio_api: true
init: false
homeassistant: 0.92.0b2
timeout: 20
ports:
  80/tcp: null
  443/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress i.e. Sidebar)
  443/tcp: Web interface SSL (Not required for Ingress i.e. Sidebar)
auth_api: true
map:
- ssl
- share:rw
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  system_packages: []
  init_commands: []
  leave_front_door_open: false
schema:
  ssl: bool
  certfile: str
  keyfile: str
  system_packages:
  - str
  init_commands:
  - str
  leave_front_door_open: bool?
image: ghcr.io/expaso/pgadmin4/{arch}
